-- ==========================================================================
-- SCRIPT SETUP DATABASE SUPABASE UNTUK WEBSITE UMKM DESA JAYAMAKMUR
-- ==========================================================================
-- Cara Penggunaan:
-- 1. Buka Dashboard Supabase Anda (https://supabase.com/dashboard)
-- 2. Pilih Proyek Anda -> Masuk ke menu "SQL Editor" (Ikon SQL di bilah kiri)
-- 3. Klik "New query", tempelkan (Paste) seluruh isi script di bawah ini, lalu klik "Run"
-- ==========================================================================

-- 1. Buat Tabel umkms
CREATE TABLE IF NOT EXISTS public.umkms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama TEXT NOT NULL,
    kategori TEXT NOT NULL,
    deskripsi TEXT,
    whatsapp TEXT,
    gambar TEXT,
    galeri JSONB DEFAULT '[]'::jsonb,
    alamat TEXT,
    "mapsUrl" TEXT,
    password TEXT DEFAULT 'owner123',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Aktifkan Row Level Security (RLS)
ALTER TABLE public.umkms ENABLE ROW LEVEL SECURITY;

-- 3. Atur Kebijakan Akses Publik (Public Policies)
-- Izinkan Baca Data secara Publik
DROP POLICY IF EXISTS "Allow public read access" ON public.umkms;
CREATE POLICY "Allow public read access" ON public.umkms FOR SELECT USING (true);

-- Izinkan Tambah Data secara Publik
DROP POLICY IF EXISTS "Allow public insert access" ON public.umkms;
CREATE POLICY "Allow public insert access" ON public.umkms FOR INSERT WITH CHECK (true);

-- Izinkan Edit Data secara Publik
DROP POLICY IF EXISTS "Allow public update access" ON public.umkms;
CREATE POLICY "Allow public update access" ON public.umkms FOR UPDATE USING (true);

-- Izinkan Hapus Data secara Publik
DROP POLICY IF EXISTS "Allow public delete access" ON public.umkms;
CREATE POLICY "Allow public delete access" ON public.umkms FOR DELETE USING (true);
